---
- name: Install and start apache web server
  hosts: web
  become: yes
  gather_facts: false
  vars:
    httpd_packages: httpd

  tasks:
    - name: install apache
      yum:
        name: "{{ httpd_packages }}"
        state: present
      
    - name: start apache
      service:
        name: httpd
        state: started
